services:
  nginx:
    image: nginx:latest
    container_name: tei-load-balancer
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - tei-net
    restart: unless-stopped
    depends_on:
      # 依赖关系将由启动脚本动态添加
      - tei-0
      - tei-1

# 网络定义
networks:
  tei-net:
    driver: bridge