# configs/train_config.yaml

# -------------------
# 模型相关配置
# -------------------
model:
  name: "Qwen/Qwen3-Embedding-0.6B"
  max_length: 2048
  quantization_bits: 4 # <--- 回归到使用这个参数
  instruction: "Represent this LLVM IR for searching for similar functions:"

# -------------------
# LoRA (PEFT) 配置
# -------------------
lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  # 目标模块通常比Unsloth少，这是标准的QLoRA设置
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
  bias: "none"

# -------------------
# 数据相关配置
# -------------------
data:
  train_dataset_pool_path: "data/processed_dataset/train_dataset_pool"
  train_positive_map_path: "data/processed_dataset/train_positive_map.pkl"
  validation_dataset_pool_path: "data/processed_dataset/validation_dataset_pool"
  validation_positive_map_path: "data/processed_dataset/validation_positive_map.pkl"

# -------------------
# 训练相关配置
# -------------------
training:
  output_dir: "./experiments/qwen-llvm-finetune-hf" # 建议使用新目录
  num_train_epochs: 3
  
  per_device_train_batch_size: 24 # 您可以根据显存情况调整
  per_device_eval_batch_size: 16
  gradient_accumulation_steps: 4

  optim: "paged_adamw_8bit"
  learning_rate: 2.0e-5 # 建议从一个较低的学习率开始
  lr_scheduler_type: "cosine"
  warmup_ratio: 0.05

  fp16: false
  bf16: true
  gradient_checkpointing: true

  logging_strategy: "steps"
  logging_steps: 10
  eval_strategy: "steps"
  eval_steps: 500
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

  dataloader_num_workers: 8
  
  remove_unused_columns: false

  triplet_margin: 1.0
  label_names: []
